### ISSUE TITLE
Add Google Analytics to Viewer

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#3]
I'd like to know how much traffic the viewer is getting. Is there a way to add Google Analytics to it? Not sure if need to use Ladybug Tools' Analytics account (if they have one) or Carmel's.

**Comment by theo-armour** [comment]
@StephenRoth2014 

Really good request. Can do. We can discuss the best ways of doing this at our Wednesday meetup.

In the meantime I have invited you to the 'Spiders' team at Ladybug tools. 

You should now be able to go repo > insights > traffic to view the hits on the spider repos. There are probably more hits than show p on GitHub because of content delivery networks etc. So Google Analytics should provide more and better insights.

**Comment by theo-armour** [comment]
@StephenRoth2014 

You now have access to the https://github.com/GreenBuildingXML/ and https://github.com/ladybug-tools/spider traffic statistics provided by GitHub.

Given that neither of us are truly adept at using Google Analytics, shall we let this project drop by the wayside until there is somebody onboard who is an Analytics pro and can help derive useful insights from the data?
